threshold: 0.5 # values near to 0 means more accurancy
# Vera IP
veraIP: 192.168.1.1
cameras:
  - url: http://....
    
    # optional username for basic authentication
    # username:
    
    # optional password for basic authentication
    # password:
    # jpeg or mjpeg supported
    type: jpeg

    # frames per seconds to analyze
    fps: 2

    # virtual device id on Vera (optional)
    veraDeviceId: 1

    # HTTP uri to call in POST (optional)
    webHook: